'use client';

import { useRouter } from 'next/navigation';
import { useDispatcherScope } from '../../_components/dispatcher-context';
import { PageHeader } from '../../_components/ui';
import { LoadingState } from '../../../../components/states';
import { OutletForm } from '../_components/outlet-form';

/**
 * Dispatcher · New outlet. The identity is generated by the server on create;
 * the form only collects the mutable operating fields.
 */
export function NewOutletScreen() {
  const router = useRouter();
  const { depots } = useDispatcherScope();

  return (
    <>
      <PageHeader
        title="Add outlet"
        description="A new outlet is created with a server-assigned id and immediately available to planning."
        actions={
          <button
            type="button"
            onClick={() => router.push('/dispatcher/outlets')}
            className="tap-target rounded-control bg-card px-4 text-sm font-medium text-ink ring-1 ring-ink/15 hover:bg-page"
          >
            Back to outlets
          </button>
        }
      />
      {depots && depots.length > 0 ? (
        <OutletForm depots={depots} />
      ) : (
        <LoadingState label="Loading depots…" />
      )}
    </>
  );
}
